name: wedevs_flutter_project
description: Wedevs Flutter Project
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  dio: ^4.0.4
  get_storage: ^2.0.3
  flutter_svg: ^1.0.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  google_fonts: ^2.2.0
  flutter_rating_bar: ^4.0.0
  simple_animations: ^3.0.0
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.4+4
  dotted_border: ^2.0.0+2
  html: ^0.15.0
  email_validator: ^2.0.1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/response.json
  uses-material-design: true
